# To build the documentation use `build.py`

site_name: nodecg-io Documentation
site_author: codeoverflow.org
site_url: https://nodecg.io/
copyright: 'Â© 2020 codeoverflow.org CC-BY-4.0'

theme:
  palette:
    scheme: slate
    primary: teal
  name: material
  font: false
  feature:
    tabs: true
  favicon: https://avatars.githubusercontent.com/codeoverflow-org

docs_dir: docs
site_dir: build

repo_name: codeoverflow-org/nodecg-io
repo_url: https://github.com/codeoverflow-org/nodecg-io
edit_uri: https://github.com/codeoverflow-org/nodecg-io-docs/edit/master/docs/

markdown_extensions:
    - plantuml_markdown:
        server: http://www.plantuml.com/plantuml 
    - markdown_checklist.extension

nav:
  - Home: index.md
  - Install: install.md
  - How to Contribute:
    - Basics: contribute.md
    - Create a Service: contribute/create_service.md
    - Create a sample bundle: contribute/create_sample.md
    - Document a sample: contribute/sample_documentation.md
  - Available services: services.md
  - Dependency Graph: dependencies.md
  - Sample Implementations:
    - Discord: samples/discord.md
    - IntelliJ: samples/intellij.md
    - Rcon: samples/rcon.md
    - Twitch: samples/twitch.md
    - WebSocket:
      - Client: samples/ws-client.md
      - Server: samples/ws-server.md
  - Create your first bundle: create_bundle.md
  - Contributors: contributors.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sX2Gjbs