site_name: nodecg-io Documentation
site_author: codeoverflow.org
site_url: https://nodecg.io/
copyright: "Â© 2020 codeoverflow.org CC-BY-4.0"

theme:
    palette:
        scheme: slate
    #  primary: teal
    name: material
    font: false
    features:
        - tabs
    logo: assets/logo.png
    favicon: assets/logo.png

docs_dir: docs
site_dir: build

repo_name: codeoverflow-org/nodecg-io
repo_url: https://github.com/codeoverflow-org/nodecg-io
edit_uri: https://github.com/codeoverflow-org/nodecg-io-docs/edit/master/docs/

markdown_extensions:
    - plantuml_markdown:
          server: http://www.plantuml.com/plantuml
    - codehilite:
          noclasses: true
          use_pygments: true
          pygments_style: monokai
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tasklist:
          custom_checkbox: true

nav:
    - Home: index.md
    - Getting Started:
          - Installation: getting_started/install.md
          - Using a sample bunndle: getting_started/try_example_bundle.md
          - Your first bundle: getting_started/create_new_bundle.md
          - Migrating an existing bundle: getting_started/existing_bundle.md
          - Configuration: getting_started/configuration.md
    - Contribute:
          - Basics: contribute/contribute.md
          - Create a Service: contribute/create_service.md
          - Create a sample bundle: contribute/create_sample.md
          - Document a sample: contribute/sample_documentation.md
          - Contributors: contribute/contributors.md
    - Services:
          - Available services: services.md
          - AHK sample: samples/ahk.md
          - Art-Net sample: samples/artnet.md
          - Curseforge sample: samples/curseforge.md
          - Android: samples/android.md
          - DBus: samples/dbus-ratbagd.md
          - Debug: samples/debug.md
          - Discord:
                - Discord API sample: samples/discord.md
                - Discord RPC sample: samples/discord-rpc.md
          - GitHub sample: samples/github.md
          - Googleapis:
                - GSheets sample: samples/gsheets.md
                - Youtube sample: samples/youtube.md
          - IntelliJ sample: samples/intellij.md
          - IRC: samples/irc.md
          - Midi:
                - Midi-Input sample: samples/midi-input.md
                - Midi-Output sample: samples/midi-output.md
                - Midi-IO sample: samples/midi-io.md
          - MQTT: samples/mqtt-client.md
          - Nanoleaf: samples/nanoleaf.md
          - OBS: samples/obs.md
          - Philips Hue sample: samples/philipshue.md
          - Rcon sample: samples/rcon.md
          - Reddit sample: samples/reddit.md
          - sACN:
                - sACN Receiver sample: samples/sacn-receiver.md
                - sACN Sender sample: samples/sacn-sender.md
          - Serial sample: samples/serial.md
          - Shlink sample: samples/shlink.md
          - Slack sample: samples/slack.md
          - Spotify sample: samples/spotify.md
          - SQL sample: samples/sql.md
          - Streamdeck sample: samples/streamdeck.md
          - StreamElements sample: samples/streamelements.md
          - Telegram sample: samples/telegram.md
          - TIANE sample: samples/tiane.md
          - Twitch:
                - Twitch-Addons sample: samples/twitch-addons.md
                - Twitch-Api sample: samples/twitch-api.md
                - Twitch-Chat sample: samples/twitch-chat.md
                - Twitch-Pubsub sample: samples/twitch-pubsub.md
          - Twitter sample: samples/twitter.md
          - WebSocket:
                - Client sample: samples/websocket-client.md
                - Server sample: samples/websocket-server.md
          - Xdotool sample: samples/xdotool.md
          - Dependency Graph: dependencies.md

extra_css:
    - stylesheets\colors.css
    - stylesheets\fonts.css

extra:
    version:
        provider: mike
    social:
        - icon: fontawesome/brands/discord
          link: https://discord.gg/sX2Gjbs
